#version 450


layout (constant_id = 0) const int N = 0;
layout (constant_id = 1) const int TS = 16;
layout (constant_id = 2) const int WPT = 8;
layout (constant_id = 3) const int RTS = TS / WPT;

layout (local_size_x_id = 1, local_size_y_id = 3, local_size_z = 1) in;


layout(set = 0, binding = 0) readonly buffer MatrixA {
    float A[];
};
layout(set = 0, binding = 1) readonly buffer MatrixB {
    float B[];
};
layout(set = 0, binding = 2) writeonly buffer MatrixC {
    float C[];
};

shared float Asub[TS][TS];
shared float Bsub[TS][TS];

void main() {
    uint M = N;
    uint K = N;

    uint row = gl_LocalInvocationID.x;
    uint col = gl_LocalInvocationID.y;
    uint globalRow = TS * gl_WorkGroupID.x + row;
    uint globalCol = TS * gl_WorkGroupID.y + col;


    float acc[WPT];
    for (int w = 0; w < WPT; w++) {
        acc[w] = 0.0;
    }


    uint numTiles = K / TS;

    for (uint t = 0; t < numTiles; t++) {
        uint tiledRow = TS * t + row;
        uint tiledCol = TS * t + col;

        // Load tiles into shared memory
        for (int w = 0; w < WPT; w++) {
            uint aIndex = globalRow * K + (tiledCol + w * RTS);
            uint bIndex = tiledRow * N + (globalCol + w * RTS);

            if (globalRow < M && globalCol + w*RTS < N) {
               Asub[row][col + w*RTS] = A[aIndex];
               Bsub[row][col + w*RTS] = B[bIndex];
            }
        }

        // Synchronise threads within the workgroup
        barrier();

        // Perform multiplication on this tile
        for (uint k = 0; k < TS; k++) {
            for (int w = 0; w < WPT; w++) {
                acc[w] += Asub[row][k] * Bsub[k][col + w * RTS];
            }
        }

        // Wait before loading next tile
        barrier();
    }

    // Write results back to global memory
    for (int w = 0; w < WPT; w++) {
        uint cIndex = globalRow * N + (globalCol + w * RTS);
        if (globalRow < M && globalCol + w*RTS < N) {
            C[cIndex] = acc[w];
         }
    }
}
