#version 450

layout(set = 0, binding = 0, std430) readonly buffer MatrixA4 {
    uvec4 dataA4[];
};

layout(set = 0, binding = 1, std430) writeonly buffer Sink {
    uint sink[];
};

layout(push_constant) uniform PC {
    uint M;        // rows
    uint N;        // cols
    uint sinkMode;
} pc;

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

void main() {
    const uint totalElems = pc.M * pc.N;          // float elements
    const uint totalVec4  = totalElems / 4u;      
    const uint threads    = gl_WorkGroupSize.x * gl_NumWorkGroups.x;
    const uint tid        = gl_GlobalInvocationID.x;

    const uint K = 64u;

    uvec4 acc4 = uvec4(0);

    // repeat over K iterations to increase runtime and make it more consistent
    for (uint rep = 0u; rep < K; ++rep) {
        for (uint i = tid; i < totalVec4; i += threads) {
            // 16-byte global load
            uvec4 v = dataA4[i];
            acc4 ^= (v + uvec4(0x9e3779b9u + rep));
        }
    }

   uint acc = acc4.x ^ acc4.y ^ acc4.z ^ acc4.w;
   // if (gl_LocalInvocationID.x == 0u) {
   //    sink[gl_WorkGroupID.x] = acc;
   // }
   sink[tid] = acc;
}
